[[main]]
identifier = 'home'
name       = 'In√≠cio'
pageRef    = '/'
weight     = 1
[[main]]
identifier = 'posts'
name       = 'Posts'
pageRef    = '/posts'
weight     = 2
[[main]]
identifier = 'about'
name       = 'Sobre'
pageRef    = '/about'
weight     = 3
[[main]]
identifier = 'tags'
name       = 'Etiquetas'
pageRef    = '/tags'
weight     = 4