[[main]]
identifier = 'home'
name       = 'Home'
pageRef    = '/'
weight     = 1
[[main]]
identifier = 'posts'
name       = 'Categories'
pageRef    = '/posts'
weight     = 2
[[main]]
identifier = 'about'
name       = 'About'
pageRef    = '/about'
weight     = 3
[[main]]
identifier = 'tags'
name       = 'Tags & Stats'
pageRef    = '/tags'
weight     = 4
