baseURL = "https://maeka.com.br"
languageCode = "pt"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true
title = "MAEKA WEB STRATEGY"
theme = "ink-free"
pagination.pagerSize = 5


copyright = "© Copyright notice"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]


[languages]

  [languages.pt]
    contentDir   = "content/pt"
    languageName = "Português"
    weight       = 1

    [languages.pt.permalinks]
      posts = "/:sections/:slug/"

  [languages.en]
    contentDir   = "content/en"
    languageName = "English"
    weight       = 2

    [languages.en.permalinks]
      posts = "/:sections/:slug/"


[params.author]
name  = "Ricardo Maekawa"
image = "/img/ricardo-maekawa.jpeg"
avatar = "/img/ricardo-maekawa.jpeg"

[params.author.bio]
pt = "Estrategista de comunicação digital."
en = "Digital communication strategist."



[params]
	subtitle = "Mess is the order you can't understand. [Ricardo Maekawa](https://www.linkedin.com/in/maeka/) has a website."


	customCSS = "css/overrides.css"


	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false
	mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"

	# Google Analytics alternative
	enableUmami = false
	umamiURL = "https://umami.yourdomain/script.js"
	umamiWebsiteId = "123-456-789"

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	footers = [
		"What Tiger King can teach us about x86 Assembly",
		"10 Reasons why gcc SHOULD be re-written in JavaScript - You won't believe #8!"
	]

	# Github base url
	github = "https://github.com/maeka"

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = true
	referenceBookWords = 11500.0
	referenceBook = "The Metamorphosis"
	referenceAuthor = "Franz Kafka"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags & Stats"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url  = "/categories"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/maeka"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/logsdebusca"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

